### Get all orders
GET http://localhost:5000/api/order

### Get an order by ID
GET http://localhost:5000/api/order/1

### Create a new order
POST http://localhost:5000/api/order
Content-Type: application/json

{
  "customerId": 2,
  "orderDate": "2025-04-25T16:59:39.174045",
  "deliveryAddress": "Deltaweg 88, Zeeland",
  "expectedDeliveryDate": "2025-04-30T16:59:39.174113",
  "status": "Delivered",
  "productLines": [
    {
      "productId": 1,
      "quantity": 6
    }
  ],
  "shipmentOrders": [
    {
      "shipmentId": 2
    }
  ]
}


### Update an existing order
PUT http://localhost:5000/api/order/1
Content-Type: application/json

{
  "customerId": 2,
  "orderDate": "2025-04-29T00:00:00",
  "deliveryAddress": "5678 Elm St",
  "expectedDeliveryDate": "2025-05-03T00:00:00",
  "status": "Processing",
  "productLines": [
    {
      "productId": 2,
      "quantity": 5
    }
  ]
}

### Soft delete an order
DELETE http://localhost:5000/api/orders/1
